name: HolographicChat
version: 0.1
description: The perfect chat display Plugin
author: Claudiordev
softdepend: [HolographicDisplays]
main: com.claudiordev.main.Main
api-version: 1.15
commands:
  hdchat:
    description: Main command plugin
    usage: /hdchat